### ISSUE TITLE
0.2.1 tag missing

### ISSUE THREAD

**Issue by glensc** [shin-/dockerpy-creds#4]
pypi has 0.2.1
https://pypi.python.org/pypi/docker-pycreds

but this repo only 0.2.0:
https://github.com/shin-/dockerpy-creds/releases

i assume this is the upstream repo as the url specified in [0.1.0](https://pypi.python.org/pypi/docker-pycreds/0.1.0) is inexistent:
https://github.com/docker/docker-pycreds/

**Comment by shin-** [comment]
Done :+1:
