### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by komuw** [shin-/dockerpy-creds#7]
hi, it looks like this lib doesn't support windows yet[1]
- is that the correct assesment?
- if that is correct; how does docker-compose/docker-py work on windows credstore?
- if docker-compose/docker-py does not currently work with windows credstore, would you mind if I send you a PR for that here?

ref:
1. https://github.com/shin-/dockerpy-creds/blob/master/dockerpycreds/constants.py#L2-L3 

PS: I bumped into this lib when working on; https://github.com/komuW/meli/issues/64 so thanks for your work.

**Comment by komuw** [comment]
cc @shin-

**Comment by shin-** [comment]
Hi @komuw 

There's no reason this package shouldn't work on Windows as well ; but if you do find a bug, please report it here.
